obj-$(CONFIG_UNION_FS) += unionfs.o

unionfs-y := subr.o dentry.o file.o inode.o main.o super.o \
	stale_inode.o branchman.o rdstate.o copyup.o dirhelper.o \
	rename.o unlink.o lookup.o commonfops.o dirfops.o sioq.o
